### ISSUE TITLE
Add % return for each coin as well as an overall % return for portfolio

### ISSUE THREAD

**Issue by Alonzo** [nsidawy/CryptoTax#2]
It would be great to see what kind of gains exist for each coin (percent and absolute but % probably first). It would also be good to add a weighted average buy price to show where you got in and if you should add to your position

**Comment by nsidawy** [comment]
Interesting idea. How would the math work for weighted average? Are sells accounted for?

**Comment by Alonzo** [comment]
price weighted by # units bought. Sells would assume LIFO and reduce the # units bought at the latest price point.

**Comment by nsidawy** [comment]
Done
