### ISSUE TITLE
more space for portfolio review area

### ISSUE THREAD

**Issue by Alonzo** [nsidawy/CryptoTax#3]
Right now each section has the same height. Making the app full screen allows the last section to be larger. With a long portfolio, it would be better to see it all at once. Can you make it so each section is dynamic in height? Or can we do a split screen approach where portfolio on left and then other stuff on right?

**Comment by Alonzo** [comment]
New recommendation: split screen approach (left is summary, right is transaction log). This is in 1 main tab and you have a 2nd tab for taxes. I think separating the views would be best

**Comment by nsidawy** [comment]
Pushed out a version with all panels in their own tab. Its on a branch called "tabs".

Lemme know what you think. Can also try the configuration you suggested.

**Comment by Alonzo** [comment]
Split view and tabs look great. 

A few minor enhancements:
- reduce percision on % return. you dont need decimals (or just 1 decimal)
- Price in USD column should remove trailing 0s
- by default can you give the portfolio side more space as it is primary use case like 70% width
- Can you make market cap be abbreviated like 22B, 21.5M, etc? a short form would be cool
- Any currencies that have been exited (0 amount) should always be on bottom regardless of sort
- CryptoCurrencyAmount column should just read Quantity
- CryptoCurrency column can be Crypto (technically not everything a currency and its shorter)
- USDAmount column should read TotalUSD

**Comment by Alonzo** [comment]
Ignore the "by default can you give the portfolio side more space as it is primary use case like 70% width"

I think going back to previous layout which has vertical split is better (especially now that taxes are in sep. tab)

**Comment by nsidawy** [comment]
Cool. Will do. All those formatting changes are easy too.

**Comment by nsidawy** [comment]
Rather than sorting things that are 0 in your portfolio to the bottom,  I am just  going to hide it.
