### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by Alonzo** [nsidawy/CryptoTax#5]
Not sure how often the portfolio section refreshes but i would like to click a button in a panic F5 kind of way

**Comment by nsidawy** [comment]
It refreshes every 15 seconds but that's actually faster than how quickly the coin market cap api updates its values. So smashing F5 would be very unsatisfying.

Does it still seem worth it?

**Comment by nsidawy** [comment]
@Alonzo bump

**Comment by Alonzo** [comment]
nah, i can see it now refreshing. totally fine.
